root = '.'
tmp_dir = 'tmp'
testdata_dir = 'testdata'

[build]
cmd = 'docker-compose up --build'
rerun = true

[color]
main = 'magenta'
watcher = 'cyan'
build = 'yellow'
runner = 'green'
app = ''

[log]
time = false
main_only = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
